#!/bin/bash
#**************************************************************************************
# Default Gateway Failover Script
# modified: 05.05.16 Thiago Liberati
#
# This script has to be run as root, because of modifying the routing tables.
# It should be run in background (e.g. scriptname &)
#
# needed packages:
# - iproute2
#
# functions:
# - checking if internet are reachable via default gateway
# - switching to backup gateway if needed
# - switching back to default gateway if all is ok again
# - writes each gateway switch to logfile
# - it does NOT check if internet is working via the backup gateway
#**************************************************************************************
#*********************************************************************
# Configuration part
#*********************************************************************
DEF_GATEWAY="201.48.5.206" # Default Gateway (e.g. Loadbalancer)
BCK_GATEWAY="177.84.240.1" # Backup Gateway
RMT_IP_1="200.221.2.45" # first remote ip (uol.com.br)
RMT_IP_2="200.147.67.142" # second remote ip (uol.com.br)
SLEEP_TIME="10" # time till next check in seconds
LOG_FILE="/var/log/failover.log" # logfile, default is syslog
#*********************************************************************
# PLEASE CHANGE NOTHING BELOW THAT LINE !
#*********************************************************************
# functions
#
function log_time {
    date +%b' '%d' '%T
}

function check_via_def_gw {
#****************************************************************************
# function:
# - checks which gateway is used
# - checking via default gw or static routes if remote ip is reachable
#
# results
# - PING_1: result of ping to RMT_IP_1
# - PING_2: result of ping to RMT_IP_2
#****************************************************************************
# check def gw
    CURRENT_GW=`ip route show | grep default | awk '{ print $3 }'`
    if [ $CURRENT_GW == $DEF_GATEWAY ]; then
        ###echo "Running on def. gateway $CURRENT_GW"
        ping -c 2 $RMT_IP_1 > /dev/null
        PING_1=$?
        ping -c 2 $RMT_IP_2 > /dev/null
        PING_2=$?
    else
        ###echo "Not running on default gateway, currently we're running via $CURRENT_GW"
        # add static routes to remote ip's
        ip route add $RMT_IP_1 via $DEF_GATEWAY
        ip route add $RMT_IP_2 via $DEF_GATEWAY
        ping -c 2 $RMT_IP_1 > /dev/null
        PING_1=$?
        ping -c 2 $RMT_IP_2 > /dev/null
        PING_2=$?
        # del static route to remote ip's
        ip route del $RMT_IP_1
        ip route del $RMT_IP_2
    fi

}

function ip_route {
    ip=$1
    ip route del default
    ip route add default via $ip
    # flushing routing cache
    ip route flush cache
}

function warning {
    # run the whole stuff
    # checking if gateways are reachable
    ping -c 2 $DEF_GATEWAY > /dev/null
    PING_DEF_GW=$?
    ping -c 2 $BCK_GATEWAY > /dev/null
    PING_BCK_GW=$?

    if [ $PING_DEF_GW == "0" ] && [ $PING_BCK_GW == "0" ]; then
        # if gateways reachable start the loop
        echo "Default link and backup link ok"
    else
        # if gateways not reachable do not start the script
        echo "Warning, one or both defined gateways are not ok!" | tee -a $LOG_FILE
        if [ $PING_DEF_GW != "0" ]; then
            echo "Default Gateway ($DEF_GATEWAY) is NOT reachable!" | tee -a $LOG_FILE
        fi
        if [ $PING_BCK_GW != "0" ]; then
            echo "Backup Gateway ($BCK_GATEWAY) is NOT reachable!" | tee -a $LOG_FILE
        fi
        echo "Please check the gateway configuration." | tee -a $LOG_FILE
    fi
}

function failover {
#****************************************************************************
# function:
# - checks which gateway is used
# - using results of check_via_def_gw
# - switching to backup gateway if default way isn't working
# - switching back to default gateway if line is ok again
#
# used variables:
# - PING_1: result of ping to RMT_IP_1
# - PING_2: result of ping to RMT_IP_2
#****************************************************************************
# change gw if remote ip's not reachable
    if [[ $EUID -ne 0 ]]; then
            echo "Gateway Failover script must be run as root!"
            exit 1
    fi
    while true; do
        check_via_def_gw
        if [ $PING_1 != "0" ] && [ $PING_2 != "0" ]; then
            # both ip's not reachable
            # check which gw is set and change
            if [ $CURRENT_GW == $DEF_GATEWAY ]; then
                # current gateway is default gateway
                # switch to backup gateway
                ip_route $BCK_GATEWAY
                echo "$(log_time):$0-switched Gateway to Backup with IP $BCK_GATEWAY" | tee -a $LOG_FILE
            else
               # current gateway is backup gateway or manual setted gateway
               # no switch necessary
               echo "$(log_time):No switch, we're running on backup line"
               warning
           fi
        elif [ $CURRENT_GW != $DEF_GATEWAY ]; then
            # one ore both ip's are reachable
            # checks if right gw is set
            # wrong or backup default gateway is set
            # switching to default
             ip_route $DEF_GATEWAY
            echo "$(log_time):$0-Gateway switched to default with IP $DEF_GATEWAY" | tee -a $LOG_FILE
        else
            # nothing to do, gateways ok
            echo "$(log_time): default Gateway is ok, remote IP's are reachable"
            warning
        fi
    sleep $SLEEP_TIME
    done
}
# execute function failover
failover