#!/bin/bash

#===============================================================================
# Create logs files
#===============================================================================
LOG=/scripts/logs/`date +%d-%m-%Y`-syncdisk.log
 echo " " >> $LOG
 echo " " >> $LOG


TODAY=`date +%d/%m/%Y-%H:%M:%S`

echo "============================================" >> $LOG
echo "Preparing synchronizing: $TODAY             " >> $LOG
echo "                                            " >> $LOG    
echo "============================================" >> $LOG


rsync -rav /backup/disco1/   /backup/disco2/ >> $LOG

FINALDAY=`date +%d/%m/%Y-%H:%M:%S`

echo "====================================================================================" >> $LOG
echo "Backup finalized: $FINALDAY"                                                          >> $LOG
echo "====================================================================================" >> $LOG

